version: "3"
services:
    anita.wg:
        container_name: anita-wg
        env_file:
            - ./.env
        volumes:
            - ./wireguard:/etc/wireguard
        ports:
            - "${WG_PUBLIC_PORT}:51820/udp"
            - "${WG_ADMIN_PUBLIC_PORT}:51821/tcp"
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
            - net.ipv4.ip_forward=1
        restart: unless-stopped
        image: ghcr.io/wg-easy/wg-easy
        networks:
            - anita_network
networks:
  anita-network:
    external: true