version: "3"
services:
    wg:
        container_name: anita.wg
        env_file:
            - ./.env
        volumes:
            - /var/www/anita.wg/wireguard:/etc/wireguard
        ports:
            - "51820:${WG_PUBLIC_PORT}/udp"
            - "51821:${WG_ADMIN_PUBLIC_PORT}/tcp"
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
            - net.ipv4.ip_forward=1
        restart: unless-stopped
        image: ghcr.io/wg-easy/wg-easy